version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile 
    ports:
      - "8080:8080" 
